import { StrictMode,useEffect,useState } from 'react'; import {createRoot}from'react-dom/client'; import './styles.css';
const API='/api/v1';
type ProfileResponse={interfaceLanguage:string;nativeLanguage:string;timezone:string;cefrLevel:string;interests:string[]};type GoalResponse={minutesPerDay:number;daysPerWeek:number};type ConsentResponse=unknown[];type CsrfResponse={csrfToken:string};
type Data={interfaceLanguage:string;nativeLanguage:string;timezone:string;cefrLevel:string;interests:string;minutesPerDay:number;daysPerWeek:number;accepted:boolean};
const initial:Data={interfaceLanguage:'es',nativeLanguage:'es',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,cefrLevel:'A1',interests:'viajes',minutesPerDay:10,daysPerWeek:3,accepted:false};
function App(){const[auth,setAuth]=useState(false),[csrf,setCsrf]=useState(''),[data,setData]=useState(initial),[step,setStep]=useState(1),[message,setMessage]=useState(''),[practice,setPractice]=useState(false),[scenario,setScenario]=useState('restaurant'),[mode,setMode]=useState('natural'),[session,setSession]=useState<{id:string;turns:{speaker:string;text:string}[]}|null>(null),[text,setText]=useState(''),[history,setHistory]=useState<{id:string;snapshot:{scenarioSlug:string};state:string}[]>([]);
 const api=async(path:string,options:RequestInit={})=>fetch(API+path,{credentials:'include',headers:{'content-type':'application/json',...(csrf?{'x-csrf-token':csrf}:{})},...options});
 useEffect(()=>{void api('/me').then(async r=>{if(!r.ok)return;const[p,g,c,csrfResponse]=await Promise.all([api('/learner-profile'),api('/practice-goal'),api('/consent'),api('/auth/csrf')]);const pv=await p.json() as ProfileResponse|null,gv=await g.json() as GoalResponse|null,cv=await c.json() as ConsentResponse,csrfBody=await csrfResponse.json() as CsrfResponse;setCsrf(csrfBody.csrfToken);setAuth(true);if(pv)setData(x=>({...x,...pv,interests:pv.interests.join(', '),...(gv??{}),accepted:cv.length>0}));});},[]);
 const login=async()=>{const r=await api('/auth/synthetic-login',{method:'POST',body:JSON.stringify({subject:'learner-demo'})});const b=await r.json() as CsrfResponse;setCsrf(b.csrfToken);setAuth(true)};
 const save=async()=>{if(!data.accepted){setMessage('Debes aceptar la divulgación para continuar.');return;}const body={profile:{interfaceLanguage:data.interfaceLanguage,nativeLanguage:data.nativeLanguage,timezone:data.timezone,cefrLevel:data.cefrLevel,interests:data.interests.split(',').map(x=>x.trim()).filter(Boolean)},goal:{minutesPerDay:data.minutesPerDay,daysPerWeek:data.daysPerWeek},consent:{purpose:'gemini-free-ai-practice',policyVersion:'privacy-2026-09-29',providerDisclosureVersion:'gemini-free-2026-09-29',accepted:true}};const r=await api('/onboarding/complete',{method:'POST',body:JSON.stringify(body)});setMessage(r.ok?'Configuración guardada. Tu perfil está listo.':'No pudimos guardar. Revisa los campos.');};
 if(practice){const start=async()=>{const r=await api('/sessions',{method:'POST',body:JSON.stringify({scenarioSlug:scenario,level:data.cefrLevel,mode})});setSession(await r.json() as {id:string;turns:{speaker:string;text:string}[]})};const send=async()=>{if(!session)return;const r=await api(`/sessions/${session.id}/turns`,{method:'POST',body:JSON.stringify({sourceEventKey:crypto.randomUUID(),text})});setSession(await r.json() as {id:string;turns:{speaker:string;text:string}[]});setText('')};const help=async()=>{if(!session)return;const r=await api(`/sessions/${session.id}/help`,{method:'POST'});setSession(await r.json() as {id:string;turns:{speaker:string;text:string}[]})};const end=async()=>{if(!session)return;await api(`/sessions/${session.id}/end`,{method:'POST'});setSession(null);const r=await api('/sessions');setHistory(await r.json() as {id:string;snapshot:{scenarioSlug:string};state:string}[])};return <main><header><div><p className="eyebrow">FluentCoach AI</p><h1>Práctica en inglés</h1></div><button className="secondary" onClick={()=>setPractice(false)}>Perfil</button></header>{!session?<section><label>Escenario<select value={scenario} onChange={e=>setScenario(e.target.value)}>{['restaurant','travel','hotel','shopping','doctor-visit','free-conversation'].map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Modo<select value={mode} onChange={e=>setMode(e.target.value)}><option value="natural">Conversación natural</option><option value="teaching">Modo enseñanza</option></select></label><button onClick={()=>void start()}>Iniciar sesión</button><button className="secondary" onClick={()=>void api('/sessions').then(async r=>setHistory(await r.json() as {id:string;snapshot:{scenarioSlug:string};state:string}[]))}>Ver historial</button>{history.map(h=><p key={h.id}>{h.snapshot.scenarioSlug} · {h.state}</p>)}</section>:<section><div aria-live="polite">{session.turns.map((t,i)=><p key={i}><strong>{t.speaker}:</strong> {t.text}</p>)}</div><label>Tu respuesta<input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}}/></label><nav><button onClick={()=>void send()}>Enviar</button><button className="secondary" onClick={()=>void help()}>Ayuda en español</button><button className="secondary" onClick={()=>void end()}>Terminar</button></nav></section>}</main>}
 if(!auth)return <main className="signed"><p className="eyebrow">FluentCoach AI</p><h1>Practica inglés con confianza.</h1><p>Tu espacio privado para avanzar paso a paso.</p><button onClick={()=>void login()}>Entrar con identidad de desarrollo</button><small>En producción, el acceso será mediante el proveedor OIDC invitado.</small></main>;
 return <main><header><div><p className="eyebrow">FluentCoach AI</p><h1>Prepara tu aprendizaje</h1></div><span aria-label={`Paso ${step} de 3`}>Paso {step} de 3</span><button className="secondary" onClick={()=>setPractice(true)}>Practicar</button></header><div className="progress"><i style={{width:`${step/3*100}%`}}/></div>
 {step===1&&<section><h2>Cuéntanos sobre ti</h2><label>Idioma de la interfaz<select value={data.interfaceLanguage} onChange={e=>setData({...data,interfaceLanguage:e.target.value})}><option value="es">Español</option><option value="en">English</option></select></label><label>Idioma nativo<input value={data.nativeLanguage} onChange={e=>setData({...data,nativeLanguage:e.target.value})}/></label><label>Zona horaria<input value={data.timezone} onChange={e=>setData({...data,timezone:e.target.value})}/></label><fieldset><legend>Tu nivel de inglés</legend><div className="levels">{['A1','A2','B1','B2'].map(x=><label key={x}><input type="radio" name="level" checked={data.cefrLevel===x} onChange={()=>setData({...data,cefrLevel:x})}/>{x}</label>)}</div></fieldset><label>Intereses (separados por comas)<input value={data.interests} onChange={e=>setData({...data,interests:e.target.value})}/></label></section>}
 {step===2&&<section><h2>Tu ritmo de práctica</h2><p>Te proponemos 10 minutos, 3 días por semana. Puedes cambiarlo.</p><label>Minutos por día<input type="number" min="5" max="120" value={data.minutesPerDay} onChange={e=>setData({...data,minutesPerDay:+e.target.value})}/></label><label>Días por semana<input type="number" min="1" max="7" value={data.daysPerWeek} onChange={e=>setData({...data,daysPerWeek:+e.target.value})}/></label></section>}
 {step===3&&<section><h2>Privacidad y práctica con IA</h2><div className="notice"><strong>Divulgación Gemini Free · versión 2026-09-29</strong><p>Cuando activemos las funciones de IA en futuros hitos, FluentCoach usará la API Gemini Developer sin pago para este piloto de coste cero. El contenido enviado en el nivel gratuito puede ser utilizado por Google para mejorar sus productos y puede ser revisado por personas, de acuerdo con sus términos vigentes.</p><p>FluentCoach no almacenará audio sin procesar. Puedes decidir no continuar con la práctica basada en IA.</p></div><label className="check"><input type="checkbox" checked={data.accepted} onChange={e=>setData({...data,accepted:e.target.checked})}/>He leído y acepto explícitamente esta divulgación.</label></section>}
 <nav>{step>1&&<button className="secondary" onClick={()=>setStep(step-1)}>Atrás</button>}{step<3?<button onClick={()=>setStep(step+1)}>Continuar</button>:<button onClick={()=>void save()}>Aceptar y guardar</button>}</nav><p role="status">{message}</p></main>}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
