import { randomUUID } from 'node:crypto';
import { beforeEach,describe,expect,it } from 'vitest';
import { PostgresVocabularyRepository,sql } from '@fluentcoach/infrastructure';
import { vocabularyIdentity } from '@fluentcoach/domain';
import { account,resetDatabase } from '../support/database.js';
describe('vocabulary confirmation and reviews',()=>{
 beforeEach(resetDatabase);
 async function suggestion(accountId:string,phrase='Take a seat',sense='Please sit down') { const profile=(await sql<{id:string}>('SELECT id FROM learner_profiles WHERE account_id=$1',[accountId]))[0]!.id;const sessionId=(await sql<{id:string}>("INSERT INTO practice_sessions(account_id,profile_id,scenario_slug,scenario_version,level,mode,prompt_version,state,transcript_revision) VALUES($1,$2,'hotel',1,'A2','NATURAL','tutor-v4','ENDED',1) RETURNING id",[accountId,profile]))[0]!.id;const run=(await sql<{id:string}>("INSERT INTO analysis_runs(session_id,account_id,transcript_revision,analyzer_version,status) VALUES($1,$2,1,'analysis-v3','SUCCEEDED') RETURNING id",[sessionId,accountId]))[0]!.id;const reportId=(await sql<{id:string}>("INSERT INTO session_reports(analysis_run_id,session_id,account_id,transcript_revision,schema_version,content) VALUES($1,$2,$3,1,'report-v1','{}') RETURNING id",[run,sessionId,accountId]))[0]!.id;const identity=vocabularyIdentity(phrase,sense); return (await sql<{id:string}>(`INSERT INTO vocabulary_suggestions(account_id,phrase,normalized_phrase,meaning,normalized_sense,source_session_id,source_report_id,source_revision,evidence,origin_version) VALUES($1,$2,$3,$4,$5,$6,$7,1,'{}','vocabulary-suggestion-v1') RETURNING id`,[accountId,phrase,identity.normalizedPhrase,sense,identity.normalizedSense,sessionId,reportId]))[0]!.id; }
 it('confirms idempotently, queues due cards, advances once and rejects stale versions',async()=>{const a=await account('review-a'),repo=new PostgresVocabularyRepository(),id=await suggestion(a.id);const [first,second]=await Promise.all([repo.confirm(a.id,id),repo.confirm(a.id,id)]);expect(first.id).toBe(second.id);expect(await repo.due(a.id,20)).toHaveLength(1);const key=randomUUID(),result=await repo.review(a.id,first.id,{rating:'good',reviewKey:key,expectedVersion:1});expect((await repo.review(a.id,first.id,{rating:'good',reviewKey:key,expectedVersion:1})).review.id).toBe(result.review.id);await expect(repo.review(a.id,first.id,{rating:'easy',reviewKey:randomUUID(),expectedVersion:1})).rejects.toThrow('STALE_CARD_VERSION');expect(await repo.due(a.id,20)).toHaveLength(0);expect(await repo.history(a.id,first.id)).toHaveLength(1);});
 it('ignores without a card and enforces two-account ownership',async()=>{const a=await account('review-owner'),b=await account('review-attacker'),repo=new PostgresVocabularyRepository(),id=await suggestion(a.id);await repo.ignore(a.id,id);expect(await repo.listCards(a.id)).toEqual([]);await expect(repo.confirm(b.id,id)).rejects.toThrow('VOCABULARY_NOT_FOUND');const own=await suggestion(a.id,'Check in','arrive at hotel'),card=await repo.confirm(a.id,own);await expect(repo.history(b.id,card.id)).rejects.toThrow('VOCABULARY_NOT_FOUND');await expect(repo.review(b.id,card.id,{rating:'again',reviewKey:randomUUID(),expectedVersion:1})).rejects.toThrow('VOCABULARY_NOT_FOUND');});
 it('deduplicates phrase plus sense but preserves a different sense',async()=>{const a=await account('review-dedup'),repo=new PostgresVocabularyRepository();const x=await suggestion(a.id,'Bank!','financial institution'),y=await suggestion(a.id,'bank','financial institution'),z=await suggestion(a.id,'bank','river edge');expect((await repo.confirm(a.id,x)).id).toBe((await repo.confirm(a.id,y)).id);await repo.confirm(a.id,z);expect(await repo.listCards(a.id)).toHaveLength(2);});
});
