CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE "AccountStatus" AS ENUM ('ACTIVE','DISABLED','DELETING');
CREATE TYPE "CefrLevel" AS ENUM ('A1','A2','B1','B2');
CREATE TABLE accounts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), oidc_issuer TEXT NOT NULL, oidc_subject TEXT NOT NULL, status "AccountStatus" NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(oidc_issuer,oidc_subject));
CREATE TABLE learner_profiles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), account_id UUID NOT NULL UNIQUE REFERENCES accounts(id) ON DELETE CASCADE, interface_language VARCHAR(16) NOT NULL, native_language VARCHAR(16) NOT NULL, timezone VARCHAR(64) NOT NULL, cefr_level "CefrLevel" NOT NULL, interests TEXT[] NOT NULL, onboarding_version INTEGER, version INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(id,account_id));
CREATE TABLE practice_goals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), account_id UUID NOT NULL UNIQUE REFERENCES accounts(id) ON DELETE CASCADE, minutes_per_day INTEGER NOT NULL DEFAULT 10 CHECK(minutes_per_day BETWEEN 5 AND 120), days_per_week INTEGER NOT NULL DEFAULT 3 CHECK(days_per_week BETWEEN 1 AND 7), effective_from TIMESTAMPTZ NOT NULL DEFAULT now(), version INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE consent_records (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), account_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE, purpose VARCHAR(80) NOT NULL, policy_version VARCHAR(40) NOT NULL, provider_disclosure_version VARCHAR(40) NOT NULL, accepted_at TIMESTAMPTZ NOT NULL DEFAULT now(), revoked_at TIMESTAMPTZ, UNIQUE(account_id,purpose,policy_version,provider_disclosure_version,accepted_at));
CREATE INDEX consent_records_account_purpose_accepted_idx ON consent_records(account_id,purpose,accepted_at);
-- RLS is intentionally deferred by ADR 0007; the runtime role has no table-owner bypass assumptions.
