import{Body,ConflictException,Controller,Get,Post,Put,Req,UseGuards}from'@nestjs/common';import{pool,sql}from'@fluentcoach/infrastructure';import{consentInput,learnerProfileInput,onboardingInput,practiceGoalInput}from'@fluentcoach/contracts';import{AuthGuard,type AuthRequest}from'./auth.guard.js';import{CsrfGuard}from'./csrf.guard.js';
@Controller('api/v1')@UseGuards(AuthGuard)export class LearnerController{
@Get('learner-profile')async profile(@Req()r:AuthRequest){return(await sql('SELECT interface_language AS "interfaceLanguage",native_language AS "nativeLanguage",timezone,cefr_level AS "cefrLevel",interests,version,onboarding_version AS "onboardingVersion" FROM learner_profiles WHERE account_id=$1',[r.accountId]))[0]??null;}
@Put('learner-profile')@UseGuards(CsrfGuard)async putProfile(@Req()r:AuthRequest,@Body()raw:unknown){const v=learnerProfileInput.parse(raw);const rows=await sql(`INSERT INTO learner_profiles(account_id,interface_language,native_language,timezone,cefr_level,interests) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(account_id) DO UPDATE SET interface_language=$2,native_language=$3,timezone=$4,cefr_level=$5,interests=$6,version=learner_profiles.version+1,updated_at=now() WHERE $7::int IS NULL OR learner_profiles.version=$7 RETURNING *`,[r.accountId,v.interfaceLanguage,v.nativeLanguage,v.timezone,v.cefrLevel,v.interests,v.version??null]);if(!rows[0])throw new ConflictException('STALE_VERSION');return rows[0];}
@Get('practice-goal')async goal(@Req()r:AuthRequest){return(await sql('SELECT minutes_per_day AS "minutesPerDay",days_per_week AS "daysPerWeek",version FROM practice_goals WHERE account_id=$1',[r.accountId]))[0]??null;}
@Put('practice-goal')@UseGuards(CsrfGuard)async putGoal(@Req()r:AuthRequest,@Body()raw:unknown){const v=practiceGoalInput.parse(raw);return(await sql(`INSERT INTO practice_goals(account_id,minutes_per_day,days_per_week) VALUES($1,$2,$3) ON CONFLICT(account_id) DO UPDATE SET minutes_per_day=$2,days_per_week=$3,version=practice_goals.version+1,updated_at=now() RETURNING *`,[r.accountId,v.minutesPerDay,v.daysPerWeek]))[0];}
@Get('consent')consent(@Req()r:AuthRequest){return sql('SELECT purpose,policy_version AS "policyVersion",provider_disclosure_version AS "providerDisclosureVersion",accepted_at AS "acceptedAt",revoked_at AS "revokedAt" FROM consent_records WHERE account_id=$1 ORDER BY accepted_at DESC',[r.accountId]);}
@Post('consent')@UseGuards(CsrfGuard)async addConsent(@Req()r:AuthRequest,@Body()raw:unknown){const v=consentInput.parse(raw);return(await sql('INSERT INTO consent_records(account_id,purpose,policy_version,provider_disclosure_version) VALUES($1,$2,$3,$4) RETURNING *',[r.accountId,v.purpose,v.policyVersion,v.providerDisclosureVersion]))[0];}
@Post('onboarding/complete')@UseGuards(CsrfGuard)async complete(@Req()r:AuthRequest,@Body()raw:unknown){const v=onboardingInput.parse(raw),c=await pool.connect();try{await c.query('BEGIN');await c.query(`INSERT INTO learner_profiles(account_id,interface_language,native_language,timezone,cefr_level,interests,onboarding_version)VALUES($1,$2,$3,$4,$5,$6,1)ON CONFLICT(account_id)DO UPDATE SET interface_language=$2,native_language=$3,timezone=$4,cefr_level=$5,interests=$6,onboarding_version=1,version=learner_profiles.version+1,updated_at=now()`,[r.accountId,v.profile.interfaceLanguage,v.profile.nativeLanguage,v.profile.timezone,v.profile.cefrLevel,v.profile.interests]);await c.query(`INSERT INTO practice_goals(account_id,minutes_per_day,days_per_week)VALUES($1,$2,$3)ON CONFLICT(account_id)DO UPDATE SET minutes_per_day=$2,days_per_week=$3,version=practice_goals.version+1,updated_at=now()`,[r.accountId,v.goal.minutesPerDay,v.goal.daysPerWeek]);await c.query('INSERT INTO consent_records(account_id,purpose,policy_version,provider_disclosure_version)VALUES($1,$2,$3,$4)',[r.accountId,v.consent.purpose,v.consent.policyVersion,v.consent.providerDisclosureVersion]);await c.query('COMMIT');return{completed:true,onboardingVersion:1};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
}
