export const LEARNER_SERVICE=Symbol('LEARNER_SERVICE');
export const ACCOUNT_REPOSITORY=Symbol('ACCOUNT_REPOSITORY');
export const CONVERSATION_SERVICE=Symbol('CONVERSATION_SERVICE');
export const JOB_SERVICE=Symbol('JOB_SERVICE');
