import type{AnalysisJob,AnalysisRun,JobStore}from'@fluentcoach/application';import{pool,sql}from'./prisma.js';
type Row={id:string;account_id:string;session_id:string;transcript_revision:number;status:'PENDING'|'RUNNING'|'SUCCEEDED'|'FAILED'|'SKIPPED';attempts:number;lease_until:Date|undefined;error_code:string|undefined};
const map=(r:Row):AnalysisRun=>({id:r.id,accountId:r.account_id,sessionId:r.session_id,revision:r.transcript_revision,status:r.status.toLowerCase()as AnalysisRun['status'],attempts:r.attempts,...(r.lease_until?{leaseUntil:r.lease_until}:{}),...(r.error_code?{errorCode:r.error_code}:{})});
export class PostgresJobStore implements JobStore{
 async finalize(i:{accountId:string;sessionId:string;hasTurns:boolean}){const c=await pool.connect();try{await c.query('BEGIN');const revision=Number((await c.query<{transcript_revision:number}>('UPDATE practice_sessions SET state=$3,ended_at=COALESCE(ended_at,now()),transcript_revision=transcript_revision+1 WHERE account_id=$1 AND id=$2 RETURNING transcript_revision',[i.accountId,i.sessionId,'ENDED'])).rows[0]?.transcript_revision);if(!revision)throw Error('SESSION_NOT_FOUND');const run=(await c.query<Row>('INSERT INTO analysis_runs(session_id,account_id,transcript_revision,analyzer_version,status)VALUES($1,$2,$3,$4,$5)ON CONFLICT(session_id,transcript_revision,analyzer_version)DO UPDATE SET session_id=EXCLUDED.session_id RETURNING *',[i.sessionId,i.accountId,revision,'fake-v1',i.hasTurns?'PENDING':'SKIPPED'])).rows[0]!;const outbox=(await c.query<{id:string}>('INSERT INTO outbox_events(account_id,aggregate_id,event_type,envelope_version,payload,dedupe_key)VALUES($1,$2,$3,1,$4,$5)ON CONFLICT(dedupe_key)DO UPDATE SET dedupe_key=EXCLUDED.dedupe_key RETURNING id',[i.accountId,i.sessionId,'analysis.requested',{analysisRunId:run.id,transcriptRevision:revision},`analysis:${run.id}`])).rows[0]!;await c.query('COMMIT');return{run:map(run),outboxId:outbox.id}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async claim(id:string,now:Date,leaseUntil:Date){const r=(await sql<Row>(`UPDATE analysis_runs SET status='RUNNING',attempts=attempts+1,lease_until=$2 WHERE id=$1 AND (status='PENDING' OR (status='RUNNING' AND lease_until<$3)) RETURNING *`,[id,leaseUntil,now]))[0];return r?map(r):null}
 async succeed(id:string,providerRunId:string){const c=await pool.connect();try{await c.query('BEGIN');await c.query("UPDATE analysis_runs SET status='SUCCEEDED',lease_until=NULL,error_code=NULL WHERE id=$1",[id]);await c.query("INSERT INTO provider_runs(id,account_id,analysis_run_id,operation,adapter,model,prompt_version,schema_version,outcome,latency_ms)SELECT $2,account_id,id,'analysis','fake','deterministic','analysis-v1','report-v1','succeeded',0 FROM analysis_runs WHERE id=$1 ON CONFLICT(id)DO NOTHING",[id,providerRunId]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}await sql('UPDATE outbox_events SET published_at=COALESCE(published_at,now()) WHERE payload->>\'analysisRunId\'=$1',[id])}
 async fail(id:string,code:string,retry:boolean){await sql(`UPDATE analysis_runs SET status=$2,lease_until=NULL,error_code=$3 WHERE id=$1`,[id,retry?'PENDING':'FAILED',code])}
 async markPublished(id:string){await sql("UPDATE outbox_events SET published_at=now(),attempts=attempts+1 WHERE payload->>'analysisRunId'=$1 AND published_at IS NULL",[id])}
 async pending(){const rows=await sql<{id:string;account_id:string;session_id:string;transcript_revision:number}>(`SELECT id,account_id,session_id,transcript_revision FROM analysis_runs WHERE status='PENDING' ORDER BY created_at`);return rows.map(r=>({version:1,analysisRunId:r.id,accountId:r.account_id,sessionId:r.session_id,transcriptRevision:r.transcript_revision})) as AnalysisJob[]}}
