import type{AnalysisJob,AnalysisRun,JobStore}from'@fluentcoach/application';import{pool,sql}from'./prisma.js';
type Row={id:string;account_id:string;session_id:string;transcript_revision:number;status:'PENDING'|'RUNNING'|'SUCCEEDED'|'FAILED'|'SKIPPED';attempts:number;lease_until:Date|undefined;error_code:string|undefined};
const map=(r:Row):AnalysisRun=>({id:r.id,accountId:r.account_id,sessionId:r.session_id,revision:r.transcript_revision,status:r.status.toLowerCase()as AnalysisRun['status'],attempts:r.attempts,...(r.lease_until?{leaseUntil:r.lease_until}:{}),...(r.error_code?{errorCode:r.error_code}:{})});
export class PostgresJobStore implements JobStore{
 async finalize(i:{accountId:string;sessionId:string;hasTurns:boolean}){const c=await pool.connect();try{await c.query('BEGIN');const session=(await c.query<{state:string;transcript_revision:number}>('SELECT state,transcript_revision FROM practice_sessions WHERE account_id=$1 AND id=$2 FOR UPDATE',[i.accountId,i.sessionId])).rows[0];if(!session)throw Error('SESSION_NOT_FOUND');if(session.state==='ENDED'){const existing=(await c.query<Row>('SELECT * FROM analysis_runs WHERE account_id=$1 AND session_id=$2 AND transcript_revision=$3 ORDER BY created_at DESC LIMIT 1',[i.accountId,i.sessionId,session.transcript_revision])).rows[0];if(!existing)throw Error('FINALIZATION_INCOMPLETE');const outbox=(await c.query<{id:string}>('SELECT id FROM outbox_events WHERE dedupe_key=$1',[`analysis:${existing.id}`])).rows[0];if(!outbox)throw Error('FINALIZATION_INCOMPLETE');await c.query('COMMIT');return{run:map(existing),outboxId:outbox.id}}const revision=session.transcript_revision+1;await c.query(`UPDATE practice_sessions SET state='ENDED',ended_at=now(),transcript_revision=$3 WHERE account_id=$1 AND id=$2`,[i.accountId,i.sessionId,revision]);const run=(await c.query<Row>('INSERT INTO analysis_runs(session_id,account_id,transcript_revision,analyzer_version,status)VALUES($1,$2,$3,$4,$5) RETURNING *',[i.sessionId,i.accountId,revision,'fake-v1',i.hasTurns?'PENDING':'SKIPPED'])).rows[0]!;const outbox=(await c.query<{id:string}>('INSERT INTO outbox_events(account_id,aggregate_id,event_type,envelope_version,payload,dedupe_key)VALUES($1,$2,$3,1,$4,$5) RETURNING id',[i.accountId,i.sessionId,'analysis.requested',{version:1,analysisRunId:run.id,accountId:i.accountId,sessionId:i.sessionId,transcriptRevision:revision},`analysis:${run.id}`])).rows[0]!;await c.query('COMMIT');return{run:map(run),outboxId:outbox.id}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async claim(id:string,now:Date,leaseUntil:Date){const r=(await sql<Row>(`UPDATE analysis_runs SET status='RUNNING',attempts=attempts+1,lease_until=$2 WHERE id=$1 AND (status='PENDING' OR (status='RUNNING' AND lease_until<$3)) RETURNING *`,[id,leaseUntil,now]))[0];return r?map(r):null}
 async succeed(id:string,providerRunId:string){const c=await pool.connect();try{await c.query('BEGIN');await c.query("UPDATE analysis_runs SET status='SUCCEEDED',lease_until=NULL,error_code=NULL WHERE id=$1",[id]);await c.query("INSERT INTO provider_runs(id,account_id,analysis_run_id,operation,adapter,model,prompt_version,schema_version,outcome,latency_ms)SELECT $2,account_id,id,'analysis','fake','deterministic','analysis-v1','report-v1','succeeded',0 FROM analysis_runs WHERE id=$1 ON CONFLICT(id)DO NOTHING",[id,providerRunId]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async fail(id:string,code:string,retry:boolean){await sql(`UPDATE analysis_runs SET status=$2,lease_until=NULL,error_code=$3 WHERE id=$1`,[id,retry?'PENDING':'FAILED',code])}
 async markPublished(id:string){await sql("UPDATE outbox_events SET published_at=now(),attempts=attempts+1 WHERE payload->>'analysisRunId'=$1 AND published_at IS NULL",[id])}
 async pending(){const rows=await sql<{payload:AnalysisJob}>(`SELECT o.payload FROM outbox_events o JOIN analysis_runs a ON a.id=(o.payload->>'analysisRunId')::uuid AND a.account_id=o.account_id WHERE o.published_at IS NULL AND o.event_type='analysis.requested' AND a.status='PENDING' ORDER BY o.created_at`);return rows.map(r=>r.payload)}}
