import type { PoolClient } from 'pg';
import { validateReport, vocabularySuggestionsFromReport, type AnalysisTranscript, type VocabularyCard, type VocabularyRepository } from '@fluentcoach/application';
import { scheduleVocabularyReview, VOCABULARY_SCHEDULER_VERSION, type ReviewRating } from '@fluentcoach/domain';
import { pool } from './prisma.js';

type CardRow={id:string;phrase:string;normalized_phrase:string;meaning:string|null;state:'active'|'suspended';scheduler_version:string;due_at:Date;interval_minutes:number;repetitions:number;version:number;source_available:boolean;created_at:Date;updated_at:Date};
type SuggestionRow={id:string;phrase:string;normalized_phrase:string;meaning:string|null;normalized_sense:string;state:'pending'|'confirmed'|'ignored'|'invalidated';card_id:string|null;source_session_id:string;source_report_id:string|null;source_revision:number|null;evidence:unknown;origin_version:string;source_available:boolean;created_at:Date};
type ReviewRow={id:string;card_id:string;review_key:string;rating:ReviewRating;reviewed_at:Date;next_due_at:Date;previous_state:unknown;resulting_state:unknown};
const card=(r:CardRow):VocabularyCard=>({id:r.id,phrase:r.phrase,normalizedPhrase:r.normalized_phrase,meaning:r.meaning,state:r.state,schedulerVersion:r.scheduler_version,dueAt:r.due_at.toISOString(),intervalMinutes:r.interval_minutes,repetitions:r.repetitions,version:r.version,sourceAvailable:r.source_available,createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()});

export class PostgresVocabularyRepository implements VocabularyRepository {
 private async tx<T>(accountId:string,fn:(c:PoolClient)=>Promise<T>) { const c=await pool.connect(); try { await c.query('BEGIN'); const owner=await c.query("SELECT id FROM accounts WHERE id=$1 AND status='ACTIVE' FOR UPDATE",[accountId]); if(!owner.rowCount) throw Error('VOCABULARY_NOT_FOUND'); const value=await fn(c); await c.query('COMMIT'); return value; } catch(e){await c.query('ROLLBACK');throw e;} finally{c.release();} }
 private async rebuild(c:PoolClient,accountId:string) {
  const rows=(await c.query<{report_id:string;session_id:string;transcript_revision:number;content:unknown;turns:AnalysisTranscript['turns'];partial:boolean;scenario_slug:string;scenario_version:number;level:AnalysisTranscript['snapshot']['level'];mode:string;prompt_version:string}>(`SELECT r.id report_id,r.session_id,r.transcript_revision,r.content,t.turns,r.partial,s.scenario_slug,s.scenario_version,s.level,s.mode,s.prompt_version FROM session_reports r JOIN analysis_runs a ON a.id=r.analysis_run_id AND a.account_id=r.account_id AND a.status='SUCCEEDED' JOIN practice_sessions s ON s.id=r.session_id AND s.account_id=r.account_id AND s.transcript_revision=r.transcript_revision JOIN transcript_revisions t ON t.session_id=r.session_id AND t.revision=r.transcript_revision WHERE r.account_id=$1 ORDER BY r.id`,[accountId])).rows;
  const active:string[]=[];
  for(const r of rows){ const transcript:AnalysisTranscript={accountId,sessionId:r.session_id,revision:r.transcript_revision,turns:r.turns,partial:r.partial,synthetic:false,snapshot:{scenarioSlug:r.scenario_slug,scenarioVersion:r.scenario_version,level:r.level,mode:r.mode.toLowerCase() as AnalysisTranscript['snapshot']['mode'],promptVersion:r.prompt_version}}; let draft; try{draft=validateReport(r.content,transcript);}catch{continue;} for(const s of vocabularySuggestionsFromReport(draft,transcript)){const inserted=(await c.query<{id:string}>(`INSERT INTO vocabulary_suggestions(account_id,phrase,normalized_phrase,meaning,normalized_sense,source_session_id,source_report_id,source_revision,evidence,origin_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(account_id,source_report_id,normalized_phrase,normalized_sense) DO UPDATE SET phrase=EXCLUDED.phrase,meaning=EXCLUDED.meaning,evidence=EXCLUDED.evidence,source_available=true,updated_at=now() RETURNING id`,[accountId,s.phrase,s.normalizedPhrase,s.meaning,s.normalizedSense,s.sourceSessionId,r.report_id,s.sourceRevision,s.evidence,s.originVersion])).rows[0]!; active.push(inserted.id); } }
  await c.query(`UPDATE vocabulary_suggestions SET state='invalidated',source_available=false,source_report_id=NULL,source_revision=NULL,updated_at=now() WHERE account_id=$1 AND state='pending' AND NOT(id=ANY($2::uuid[]))`,[accountId,active]);
 }
 async listSuggestions(accountId:string){return this.tx(accountId,async c=>{await this.rebuild(c,accountId);return (await c.query<SuggestionRow>(`SELECT id,phrase,normalized_phrase,meaning,state,source_session_id,source_report_id,source_revision,evidence,origin_version,source_available,created_at FROM vocabulary_suggestions WHERE account_id=$1 AND state='pending' ORDER BY created_at,id`,[accountId])).rows.map(r=>({id:r.id,phrase:r.phrase,normalizedPhrase:r.normalized_phrase,meaning:r.meaning,state:r.state,sourceSessionId:r.source_session_id,sourceReportId:r.source_report_id,sourceRevision:r.source_revision,evidence:r.evidence,originVersion:r.origin_version,sourceAvailable:r.source_available,createdAt:r.created_at.toISOString()}));});}
 async confirm(accountId:string,id:string){return this.tx(accountId,async c=>{const s=(await c.query<SuggestionRow>(`SELECT * FROM vocabulary_suggestions WHERE id=$1 AND account_id=$2 FOR UPDATE`,[id,accountId])).rows[0];if(!s||!['pending','confirmed'].includes(s.state))throw Error('VOCABULARY_NOT_FOUND');if(s.card_id){const found=(await c.query<CardRow>('SELECT * FROM vocabulary_cards WHERE id=$1 AND account_id=$2',[s.card_id,accountId])).rows[0];if(found)return card(found);}const now=(await c.query<{now:Date}>('SELECT CURRENT_TIMESTAMP now')).rows[0]!.now;const result=(await c.query<CardRow>(`INSERT INTO vocabulary_cards(account_id,phrase,normalized_phrase,meaning,normalized_sense,source_suggestion_id,source_session_id,source_report_id,source_revision,scheduler_version,due_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(account_id,normalized_phrase,normalized_sense) DO UPDATE SET updated_at=vocabulary_cards.updated_at RETURNING *`,[accountId,s.phrase,s.normalized_phrase,s.meaning,s.normalized_sense,s.id,s.source_session_id,s.source_report_id,s.source_revision,VOCABULARY_SCHEDULER_VERSION,now])).rows[0]!;await c.query("UPDATE vocabulary_suggestions SET state='confirmed',card_id=$3,updated_at=now() WHERE id=$1 AND account_id=$2",[id,accountId,result.id]);return card(result);});}
 async ignore(accountId:string,id:string){return this.tx(accountId,async c=>{const result=await c.query("UPDATE vocabulary_suggestions SET state='ignored',updated_at=now() WHERE id=$1 AND account_id=$2 AND state='pending'",[id,accountId]);if(!result.rowCount){const existing=await c.query("SELECT 1 FROM vocabulary_suggestions WHERE id=$1 AND account_id=$2 AND state='ignored'",[id,accountId]);if(!existing.rowCount)throw Error('VOCABULARY_NOT_FOUND');}});}
 async listCards(accountId:string){return this.tx(accountId,async c=>(await c.query<CardRow>('SELECT * FROM vocabulary_cards WHERE account_id=$1 ORDER BY created_at,id',[accountId])).rows.map(card));}
 async due(accountId:string,limit:number){return this.tx(accountId,async c=>(await c.query<CardRow>("SELECT * FROM vocabulary_cards WHERE account_id=$1 AND state='active' AND due_at<=CURRENT_TIMESTAMP ORDER BY due_at,id LIMIT $2",[accountId,limit])).rows.map(card));}
 async review(accountId:string,cardId:string,input:{rating:ReviewRating;reviewKey:string;expectedVersion:number}){return this.tx(accountId,async c=>{const prior=(await c.query<ReviewRow>('SELECT * FROM vocabulary_review_events WHERE account_id=$1 AND review_key=$2',[accountId,input.reviewKey])).rows[0];if(prior){if(prior.card_id!==cardId||prior.rating!==input.rating)throw Error('IDEMPOTENCY_CONFLICT');const current=(await c.query<CardRow>('SELECT * FROM vocabulary_cards WHERE id=$1 AND account_id=$2',[cardId,accountId])).rows[0]!;return {card:card(current),review:{id:prior.id,reviewKey:prior.review_key,rating:prior.rating,reviewedAt:prior.reviewed_at.toISOString(),nextDueAt:prior.next_due_at.toISOString(),previousState:prior.previous_state,resultingState:prior.resulting_state}};}const current=(await c.query<CardRow>('SELECT * FROM vocabulary_cards WHERE id=$1 AND account_id=$2 FOR UPDATE',[cardId,accountId])).rows[0];if(!current)throw Error('VOCABULARY_NOT_FOUND');if(current.version!==input.expectedVersion)throw Error('STALE_CARD_VERSION');const reviewedAt=(await c.query<{now:Date}>('SELECT CURRENT_TIMESTAMP now')).rows[0]!.now;const previousState={intervalMinutes:current.interval_minutes,repetitions:current.repetitions,dueAt:current.due_at.toISOString(),version:current.version};const next=scheduleVocabularyReview(previousState,input.rating,reviewedAt,current.scheduler_version);const resultingState={intervalMinutes:next.intervalMinutes,repetitions:next.repetitions,dueAt:next.nextDueAt,version:current.version+1};const updated=(await c.query<CardRow>('UPDATE vocabulary_cards SET interval_minutes=$3,repetitions=$4,due_at=$5,version=version+1,updated_at=$6 WHERE id=$1 AND account_id=$2 RETURNING *',[cardId,accountId,next.intervalMinutes,next.repetitions,next.nextDueAt,reviewedAt])).rows[0]!;const event=(await c.query<ReviewRow>('INSERT INTO vocabulary_review_events(card_id,account_id,scheduler_version,review_key,previous_state,rating,reviewed_at,resulting_state,next_due_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[cardId,accountId,current.scheduler_version,input.reviewKey,previousState,input.rating,reviewedAt,resultingState,next.nextDueAt])).rows[0]!;return {card:card(updated),review:{id:event.id,reviewKey:event.review_key,rating:event.rating,reviewedAt:event.reviewed_at.toISOString(),nextDueAt:event.next_due_at.toISOString(),previousState,resultingState}};});}
 async history(accountId:string,cardId:string){return this.tx(accountId,async c=>{const exists=await c.query('SELECT 1 FROM vocabulary_cards WHERE id=$1 AND account_id=$2',[cardId,accountId]);if(!exists.rowCount)throw Error('VOCABULARY_NOT_FOUND');return (await c.query<ReviewRow>('SELECT * FROM vocabulary_review_events WHERE card_id=$1 AND account_id=$2 ORDER BY reviewed_at,id',[cardId,accountId])).rows.map(e=>({id:e.id,reviewKey:e.review_key,rating:e.rating,reviewedAt:e.reviewed_at.toISOString(),nextDueAt:e.next_due_at.toISOString(),previousState:e.previous_state,resultingState:e.resulting_state}));});}
}
